In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
data = pd.read_csv("./data/car.data")

In [6]:
data.head()

buying  maint doors persons lug_boot saftey  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [13]:
X = data[[
    "buying",
    "maint",
    "saftey"
]].values
y = data[["class"]]

In [9]:
# print(X, y)

In [25]:
# Converting X data
label_encoder = LabelEncoder()

for i in range(len(X[0])):
    X[:, i] = label_encoder.fit_transform(X[:, i])

In [26]:
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [27]:
# Converting y data
label_maping = {
    'unacc': 0,
    'acc': 1,
    'good': 2,
    'vgood': 3
}

In [28]:
y["class"] = y["class"].map(label_maping)

/var/folders/by/qcn1g28d0670bbq7bzt0y1n40000gn/T/ipykernel_60718/1149682667.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["class"] = y["class"].map(label_maping)


In [29]:
y["class"]

0       0
1       0
2       0
3       0
4       0
       ..
1723    2
1724    3
1725    0
1726    2
1727    3
Name: class, Length: 1728, dtype: int64

In [30]:
# Create a model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights="uniform")

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [33]:
knn.fit(X_train, y_train)

/Users/amitthapa/workspace/learning/ml/ml-learning/krish_naik/.venv/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [34]:
predictions = knn.predict(X_test)

In [37]:
accuracy = metrics.accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7369942196531792
